<a href="https://colab.research.google.com/github/harini1703/R-programming-Lab-Exercise/blob/main/Creating_a_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%load_ext rpy2.ipython

In [3]:
%%R
list_data1<-list("Harini","varman",89,5+9i,TRUE)
print(list_data1)

[[1]]
[1] "Harini"

[[2]]
[1] "varman"

[[3]]
[1] 89

[[4]]
[1] 5+9i

[[5]]
[1] TRUE



In [5]:
%%R
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),list("green",12.3))
print(list_data)
  

[[1]]
[1] "Jan" "Feb" "Mar"

[[2]]
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

[[3]]
[[3]][[1]]
[1] "green"

[[3]][[2]]
[1] 12.3




In [8]:
%%R
names(list_data) <- c("1st section", "Matrix", "Inner")
print(list_data)

$`1st section`
[1] "Jan" "Feb" "Mar"

$Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$Inner
$Inner[[1]]
[1] "green"

$Inner[[2]]
[1] 12.3




In [11]:
%%R
list_data2=list(c(8,6,78,90),matrix(c(8,6,89,56,45)))
print(list_data2)

[[1]]
[1]  8  6 78 90

[[2]]
     [,1]
[1,]    8
[2,]    6
[3,]   89
[4,]   56
[5,]   45



In [15]:
%%R
names(list_data2)=list(c("numbers","matrix"))
print(list_data2)

$`c("numbers", "matrix")`
[1]  8  6 78 90

$<NA>
     [,1]
[1,]    8
[2,]    6
[3,]   89
[4,]   56
[5,]   45



In [17]:
%%R
print(list_data2[1])

$`c("numbers", "matrix")`
[1]  8  6 78 90



In [18]:
%%R
print(list_data2[2])

$<NA>
     [,1]
[1,]    8
[2,]    6
[3,]   89
[4,]   56
[5,]   45



In [21]:
%%R
list_data3=list(c(89,96,85,45),matrix(c(81,96,45,78,56,23),nrow=2))
print(list_data3)


[[1]]
[1] 89 96 85 45

[[2]]
     [,1] [,2] [,3]
[1,]   81   45   56
[2,]   96   78   23



In [23]:
%%R
list_data3[4] <- "Harini"
print(list_data[4])

$<NA>
NULL



In [26]:
%%R
A<-list(c(12,12,TRUE,8+8i))
B<-list(c(78,45,FALSE,9+9i))
merged.list<-c(A,B)
print(merged.list)

[[1]]
[1] 12+0i 12+0i  1+0i  8+8i

[[2]]
[1] 78+0i 45+0i  0+0i  9+9i

